# Generated by Django 5.1 on 2024-09-06 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=200)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shuttle.event')),
            ],
        ),
        migrations.DeleteModel(
            name='photos',
        ),
    ]
